### ISSUE TITLE
service errors, no preview visible

### ISSUE THREAD

**Issue by forgi007** [FPurchess/preview-service#9]
Hello,

I have just cloned your repo master, started with docker and tried to view a jpeg image, but I get the following errors:

```
$ docker run -p 8000:8000 fpurchess/preview-service
+ mkdir -p /tmp/files
+ Xvfb :99 -screen 0 1x1x16
+ mkdir -p /tmp/cache
+ DISPLAY=:99.0
+ uvicorn --host 0.0.0.0 --port 8000 app:app
INFO:     Started server process [10]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.17.0.1:40130 - "GET /preview/100x100 HTTP/1.1" 405 Method Not Allowed
INFO:     172.17.0.1:42480 - "GET /preview/100x100 HTTP/1.1" 405 Method Not Allowed
INFO:     172.17.0.1:48554 - "POST /preview/100x100 HTTP/1.1" 400 Bad Request
INFO:     172.17.0.1:41688 - "GET /preview/100x100 HTTP/1.1" 405 Method Not Allowed
```

The curl command looks like this:

`
curl -o thumbnail.jpeg -F 'file=/home/tamas/.local/lib/python3.9/site-packages/skimage/data/coffee.png' http://localhost:8000/preview/100x100
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   244  100    35  100   209  11666  69666 --:--:-- --:--:-- --:--:-- 81333
`

Firewall is inactive, I have no other web server running. Any help is appreciated.

**Comment by ol-serdiuk** [comment]
@forgi007 put `@` before file name:
`curl -o thumbnail.jpeg -F 'file=@<path_to_your_file>' http://localhost:8000/preview/100x100`
